# Generated by Django 5.2.6 on 2025-10-03 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('free_delivery_amount', models.DecimalField(decimal_places=2, default=500, max_digits=10)),
                ('free_delivery_distance', models.DecimalField(decimal_places=2, default=5, max_digits=10)),
                ('maximum_distance', models.DecimalField(decimal_places=2, default=10, max_digits=6)),
                ('per_km_charge', models.DecimalField(decimal_places=2, default=10, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_type', models.CharField(choices=[('restaurant', 'Restaurant'), ('supermarket', 'Supermarket'), ('allmart', 'Allmart')], default='restaurant', max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('gst_number', models.CharField(max_length=15, unique=True)),
                ('contact_number', models.CharField(max_length=15)),
                ('address', models.TextField(null=True)),
                ('location', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='shop_images/')),
            ],
        ),
    ]
