# Generated by Django 5.2.6 on 2025-10-03 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Shop',
            new_name='shop',
        ),
    ]
