# Generated by Django 5.2.6 on 2025-10-06 05:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_rename_shop_order_shop'),
        ('products', '0004_remove_shopitem_gst_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL)),
                ('shop_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='products.shopitem')),
            ],
            options={
                'unique_together': {('customer', 'shop_item')},
            },
        ),
    ]
