# Generated by Django 5.2.6 on 2025-10-06 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_cart'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'ordering': ['-added_at']},
        ),
    ]
