# Generated by Django 5.2.6 on 2025-10-03 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopcategory',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.shop'),
        ),
        migrations.AddField(
            model_name='shopitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopitems', to='products.item'),
        ),
        migrations.AddField(
            model_name='shopitem',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopitems', to='shop.shop'),
        ),
        migrations.AddField(
            model_name='shopitemoffer',
            name='shop_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='products.shopitem'),
        ),
        migrations.AddField(
            model_name='shopsubcategory',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.shop'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='products.category'),
        ),
        migrations.AddField(
            model_name='shopsubcategory',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.subcategory'),
        ),
        migrations.AddField(
            model_name='item',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='products.subcategory'),
        ),
        migrations.AlterUniqueTogether(
            name='shopitem',
            unique_together={('shop', 'item')},
        ),
        migrations.AlterUniqueTogether(
            name='subcategory',
            unique_together={('category', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='item',
            unique_together={('subcategory', 'name')},
        ),
    ]
