# Generated by Django 5.2.6 on 2025-10-04 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hsn',
            old_name='cgst',
            new_name='gst',
        ),
        migrations.RenameField(
            model_name='shopitem',
            old_name='price',
            new_name='total_amount',
        ),
        migrations.RemoveField(
            model_name='hsn',
            name='igst',
        ),
        migrations.RemoveField(
            model_name='hsn',
            name='sgst',
        ),
        migrations.AddField(
            model_name='shopitem',
            name='gst_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='shopitem',
            name='taxable_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
