# Generated by Django 5.2.6 on 2025-10-04 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_cgst_hsn_gst_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopitem',
            name='gst_amount',
        ),
        migrations.RemoveField(
            model_name='shopitem',
            name='taxable_amount',
        ),
        migrations.RemoveField(
            model_name='shopitemoffer',
            name='offer_price',
        ),
        migrations.AddField(
            model_name='shopitemoffer',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shopitemoffer',
            name='max_quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='shopitemoffer',
            name='offer_pct',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=5),
            preserve_default=False,
        ),
    ]
