# Generated by Django 5.2.6 on 2025-10-20 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_shopitem_gst_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopcategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='shopcategory_images/'),
        ),
        migrations.AddField(
            model_name='shopitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='shopitem_images/'),
        ),
        migrations.AddField(
            model_name='shopsubcategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='shopsubcategory_images/'),
        ),
    ]
